uvmf:
  environments:
    add:
      agents:
      - initiator_responder: INITIATOR
        name: add_input
        type: add_in
      - initiator_responder: RESPONDER
        name: add_output
        type: add_out
      analysis_components:
      - name: add_p
        parameters: []
        type: add_pre
      - name: add_s
        parameters: []
        type: add_sb
      analysis_exports: []
      analysis_ports:
      - connected_to: add_input.monitored_ap
        name: add_input_ap
        trans_type: add_in_transaction
      - connected_to: add_output.monitored_ap
        name: add_output_ap
        trans_type: add_out_transaction
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs: []
      tlm_connections:
      - driver: add_input.monitored_ap
        receiver: add_p.add_in_ae
        validate: 'True'
      - driver: add_p.add_sb_ap
        receiver: add_s.sb_from_pre_ae
        validate: 'True'
      - driver: add_output.monitored_ap
        receiver: add_s.add_out_ae
        validate: 'True'
